package com.jim.novel.model;

import java.io.Serializable;
import java.util.Date;

public class Folder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.folder_id
     *
     * @mbg.generated
     */
    private Integer folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.father_id
     *
     * @mbg.generated
     */
    private Integer fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.sort
     *
     * @mbg.generated
     */
    private Byte sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.check
     *
     * @mbg.generated
     */
    private String check;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table folder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.folder_id
     *
     * @return the value of folder.folder_id
     *
     * @mbg.generated
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.folder_id
     *
     * @param folderId the value for folder.folder_id
     *
     * @mbg.generated
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.father_id
     *
     * @return the value of folder.father_id
     *
     * @mbg.generated
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.father_id
     *
     * @param fatherId the value for folder.father_id
     *
     * @mbg.generated
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.ename
     *
     * @return the value of folder.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.ename
     *
     * @param ename the value for folder.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.name
     *
     * @return the value of folder.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.name
     *
     * @param name the value for folder.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.path
     *
     * @return the value of folder.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.path
     *
     * @param path the value for folder.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.level
     *
     * @return the value of folder.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.level
     *
     * @param level the value for folder.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.sort
     *
     * @return the value of folder.sort
     *
     * @mbg.generated
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.sort
     *
     * @param sort the value for folder.sort
     *
     * @mbg.generated
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.width
     *
     * @return the value of folder.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.width
     *
     * @param width the value for folder.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.height
     *
     * @return the value of folder.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.height
     *
     * @param height the value for folder.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.count
     *
     * @return the value of folder.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.count
     *
     * @param count the value for folder.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.status
     *
     * @return the value of folder.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.status
     *
     * @param status the value for folder.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.check
     *
     * @return the value of folder.check
     *
     * @mbg.generated
     */
    public String getCheck() {
        return check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.check
     *
     * @param check the value for folder.check
     *
     * @mbg.generated
     */
    public void setCheck(String check) {
        this.check = check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.create_time
     *
     * @return the value of folder.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.create_time
     *
     * @param createTime the value for folder.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.modify_time
     *
     * @return the value of folder.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.modify_time
     *
     * @param modifyTime the value for folder.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.content
     *
     * @return the value of folder.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.content
     *
     * @param content the value for folder.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}