package com.jim.novel.dao;

import com.jim.novel.model.AdminFolder;

public interface AdminFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    int insert(AdminFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    int insertSelective(AdminFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    AdminFolder selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminFolder record);
}