package com.jim.novel.dao;

import com.jim.novel.model.Folder;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long folderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int insert(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int insertSelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    Folder selectByPrimaryKey(Long folderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Folder record);
}